export interface TVChannel {
  id: string;
  name: string;
  category: string;
  description: string;
  streamUrl: string;
  logoText: string;
  color: string;
  region: string;
  headers?: Record<string, string>;
}

export const categories = [
  { id: "semua", name: "Semua", icon: "📺" },
  { id: "nasional", name: "Nasional", icon: "🇮🇩" },
  { id: "berita", name: "Berita", icon: "📰" },
  { id: "hiburan", name: "Hiburan", icon: "🎬" },
  { id: "anak", name: "Anak", icon: "🧸" },
  { id: "olahraga", name: "Olahraga", icon: "⚽" },
  { id: "musik", name: "Musik", icon: "🎵" },
  { id: "religi", name: "Religi", icon: "🕌" },
  { id: "daerah", name: "Daerah", icon: "🏝️" },
  { id: "tvri", name: "TVRI", icon: "📡" },
  { id: "gaya_hidup", name: "Gaya Hidup", icon: "✨" },
  { id: "bisnis", name: "Bisnis", icon: "📊" },
];

export const regions = [
  "Semua Wilayah",
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bengkulu",
  "Lampung",
  "Bangka Belitung",
  "Banten",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Sulawesi Utara",
  "Gorontalo",
  "Sulawesi Barat",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Maluku",
  "Papua",
  "Papua Barat",
  "Nasional",
];

// Static channels as fallback when API is unavailable
// URLs sourced from iptv-org (auto-updated via /api/channels)
export const channels: TVChannel[] = [
  // ===== NASIONAL =====
  { id: "rcti_hd", name: "RCTI", category: "nasional", description: "RCTI - TV swasta pertama Indonesia", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/rcti/manifest.mpd", logoText: "RC", color: "#2563eb", region: "Nasional" },
  { id: "sctv", name: "SCTV", category: "nasional", description: "SCTV - Stasiun TV swasta nasional", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/sctv/manifest.mpd", logoText: "SC", color: "#dc2626", region: "Nasional" },
  { id: "indosiar", name: "Indosiar", category: "nasional", description: "Indosiar - TV hiburan dan informasi", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/indosiar/manifest.mpd", logoText: "IS", color: "#f59e0b", region: "Nasional" },
  { id: "transtv", name: "Trans TV", category: "nasional", description: "Trans TV - TV hiburan dan informasi", streamUrl: "https://video.detik.com/transtv/smil:transtv.smil/index.m3u8", logoText: "TT", color: "#0891b2", region: "Nasional" },
  { id: "trans7", name: "Trans7", category: "nasional", description: "Trans7 - TV hiburan dan edukasi", streamUrl: "https://video.detik.com/trans7/smil:trans7.smil/index.m3u8", logoText: "T7", color: "#059669", region: "Nasional" },
  { id: "gtv", name: "GTV", category: "nasional", description: "GTV - Stasiun TV nasional MNC Group", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/globaltv/manifest.mpd", logoText: "GT", color: "#7c3aed", region: "Nasional" },
  { id: "mnctv", name: "MNC TV", category: "nasional", description: "MNC TV - TV nasional", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/mnctv/manifest.mpd", logoText: "MN", color: "#ea580c", region: "Nasional" },
  { id: "mdtv", name: "MDTV", category: "nasional", description: "MDTV - Stasiun TV nasional Indonesia", streamUrl: "https://wahyu1ptv.pages.dev/MDTV-HD.m3u8", logoText: "MD", color: "#ea580c", region: "Nasional" },
  { id: "antv", name: "ANTV", category: "nasional", description: "ANTV - TV nasional Indonesia", streamUrl: "http://202.80.222.20/cdn/iptv/Tvod/001/channel2000022/1024.m3u8", logoText: "AN", color: "#0284c7", region: "Nasional" },
  { id: "rajawalitv", name: "Rajawali TV", category: "nasional", description: "Rajawali TV - TV nasional Indonesia", streamUrl: "https://rtvstream.rtv.co.id:4555/hls/rtv.m3u8", logoText: "RT", color: "#9333ea", region: "Nasional" },
  { id: "garudatv", name: "Garuda TV", category: "nasional", description: "Garuda TV - TV nasional Indonesia", streamUrl: "https://hgmtv.com:19360/garudatvlivestreaming/garudatvlivestreaming.m3u8", logoText: "GR", color: "#b91c1c", region: "Nasional" },
  { id: "daaitv", name: "DAAI TV", category: "nasional", description: "DAAI TV - TV inspirasi dan pendidikan", streamUrl: "https://pull.daaiplus.com/live-DAAIPLUS/live-DAAIPLUS_HD.m3u8", logoText: "DA", color: "#059669", region: "Nasional" },
  { id: "tvri_nasional", name: "TVRI Nasional", category: "nasional", description: "TVRI - TV publik nasional", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Nasional/hls/Nasional.m3u8", logoText: "TV", color: "#0d9488", region: "Nasional" },
  { id: "nusantaratv", name: "Nusantara TV", category: "nasional", description: "Nusantara TV - TV nasional Indonesia", streamUrl: "https://nusantaratv.siar.us/nusantaratv/live/playlist.m3u8", logoText: "NT", color: "#0284c7", region: "Nasional" },
  { id: "mojitv", name: "Moji", category: "nasional", description: "Moji - TV hiburan dan gaya hidup", streamUrl: "https://wahyu1ptv.pages.dev/Moji-HD.m3u8", logoText: "MJ", color: "#e11d48", region: "Nasional" },
  { id: "nickelodeon", name: "Nickelodeon", category: "nasional", description: "Nickelodeon Asia - TV anak dan kartun", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/nickelodeon/manifest.mpd", logoText: "NK", color: "#f59e0b", region: "Nasional" },
  { id: "mykidz", name: "My Kidz", category: "nasional", description: "My Kidz - Channel anak-anak", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/mykids/manifest.mpd", logoText: "MK", color: "#ec4899", region: "Nasional" },

  // ===== BERITA =====
  { id: "metrotv", name: "Metro TV", category: "berita", description: "Metro TV - Stasiun TV berita pertama di Indonesia", streamUrl: "https://edge.medcom.id/live-edge/smil:metro.smil/playlist.m3u8", logoText: "MT", color: "#0284c7", region: "Nasional" },
  { id: "tvone", name: "tvOne", category: "berita", description: "tvOne - Stasiun TV berita dan olahraga", streamUrl: "http://202.80.222.20/cdn/iptv/Tvod/001/channel2000018/1024.m3u8", logoText: "T1", color: "#dc2626", region: "Nasional" },
  { id: "kompastv", name: "Kompas TV", category: "berita", description: "Kompas TV - TV berita terpercaya", streamUrl: "https://wahyu1ptv.pages.dev/KompasTV-HD.m3u8", logoText: "KT", color: "#1d4ed8", region: "Nasional" },
  { id: "inews", name: "iNews", category: "berita", description: "iNews - TV berita MNC Group", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/inews/manifest.mpd", logoText: "iN", color: "#ea580c", region: "Nasional" },
  { id: "cnbcindonesia", name: "CNBC Indonesia", category: "berita", description: "CNBC Indonesia - TV berita bisnis dan pasar modal", streamUrl: "https://live.cnbcindonesia.com/livecnbc/smil:cnbctv.smil/master.m3u8", logoText: "CB", color: "#1e40af", region: "Nasional" },
  { id: "beritasatu", name: "BeritaSatu", category: "berita", description: "BeritaSatu - TV berita 24 jam", streamUrl: "https://beritasatu.secureswiftcontent.com/han/beritasatu/bsatu10008r/srtoutput/manifest.m3u8", logoText: "BS", color: "#0e7490", region: "Nasional" },
  { id: "magna", name: "Magna Channel", category: "berita", description: "Magna Channel - berita dan informasi", streamUrl: "https://edge.medcom.id/live-edge/smil:magna.smil/playlist.m3u8", logoText: "MG", color: "#7c3aed", region: "Nasional" },
  { id: "bnchannel", name: "BN Channel", category: "berita", description: "BN Channel - TV berita Indonesia", streamUrl: "https://flv.intechmedia.net/live/ch112.m3u8", logoText: "BN", color: "#0e7490", region: "Nasional", headers: { "http-referrer": "https://youtv.live/" } },
  { id: "sindonews", name: "Sindo News TV", category: "berita", description: "Sindo News TV - TV berita MNC Group", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/mncnews/manifest.mpd", logoText: "SN", color: "#b91c1c", region: "Nasional" },
  { id: "sinpotv", name: "Sin Po TV", category: "berita", description: "Sin Po TV - TV berita dan olahraga", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/sinpotv/manifest.mpd", logoText: "SP", color: "#9333ea", region: "Nasional" },
  { id: "btv", name: "BTV", category: "berita", description: "BTV - TV berita Indonesia", streamUrl: "https://btv.secureswiftcontent.com/han/btv/btv10005r/srtoutput/manifest.m3u8", logoText: "BV", color: "#dc2626", region: "Nasional" },
  { id: "idtv", name: "IDTV", category: "berita", description: "IDTV - TV berita Indonesia", streamUrl: "https://b1world.beritasatumedia.com/Beritasatu/B1World_manifest.m3u8", logoText: "ID", color: "#1d4ed8", region: "Nasional" },
  { id: "jakartaglobe", name: "Jakarta Globe News", category: "berita", description: "Jakarta Globe News Channel", streamUrl: "https://jktglobe.secureswiftcontent.com/han/jktglobe/jktglober/srtoutput/manifest.m3u8", logoText: "JG", color: "#0284c7", region: "Nasional" },
  { id: "radarlampungtv", name: "Radar Lampung TV", category: "berita", description: "Radar Lampung TV - TV berita Lampung", streamUrl: "https://www.streaming.radartv.co.id/hls/test.m3u8", logoText: "RL", color: "#ca8a04", region: "Lampung", headers: { "http-referrer": "https://radartvnews.com/live-streaming/" } },

  // ===== HIBURAN =====
  { id: "ficom", name: "Ficom Channel", category: "hiburan", description: "Ficom Channel - TV hiburan Indonesia", streamUrl: "https://v3.siar.us/ficomchannel/live/playlist.m3u8", logoText: "FC", color: "#7c3aed", region: "Nasional" },
  { id: "indonesiana", name: "Indonesiana.TV", category: "hiburan", description: "Indonesiana.TV - TV hiburan dan budaya", streamUrl: "https://tvstreamcast.com/indonesiana.m3u8", logoText: "ID", color: "#059669", region: "Nasional", headers: { "http-referrer": "https://indonesiana.tv/" } },
  { id: "elshintatv", name: "Elshinta TV", category: "hiburan", description: "Elshinta TV - TV hiburan dan informasi", streamUrl: "https://ams.juraganstreaming.com:5443/LiveApp/streams/elshintatv.m3u8", logoText: "ES", color: "#0e7490", region: "Nasional" },
  { id: "uchannel", name: "U Channel", category: "hiburan", description: "U Channel - TV hiburan Indonesia", streamUrl: "https://ams.juraganstreaming.com:5443/LiveApp/streams/uchannel1.m3u8", logoText: "UC", color: "#059669", region: "Nasional", headers: { "http-referrer": "https://www.u-channel.tv/" } },

  // ===== ANAK =====
  { id: "biznetkids", name: "Biznet Kids", category: "anak", description: "Biznet Kids - TV anak dan keluarga", streamUrl: "http://livestream.biznetvideo.net/biznet_kids/smil:kids.smil/index.m3u8", logoText: "BK", color: "#059669", region: "Nasional" },
  { id: "kidstv", name: "Kids TV", category: "anak", description: "Kids TV - Channel anak-anak", streamUrl: "http://origin5.mediacdn.ru/live/kidstv/index.m3u8", logoText: "KT", color: "#ec4899", region: "Nasional" },
  { id: "ananda", name: "Ananda", category: "anak", description: "Ananda - Channel anak-anak", streamUrl: "https://vodcdn.bamboo-cloud.com/livehls/68ef86320630444b1f796875/master.m3u8", logoText: "AD", color: "#f59e0b", region: "Nasional", headers: { "http-referrer": "https://anandatelkomvision.renderforestsites.com/" } },

  // ===== OLAHRAGA =====
  { id: "tvrisport", name: "TVRI Sport", category: "olahraga", description: "TVRI Sport - Channel olahraga Indonesia", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/SportHD/hls/SportHD.m3u8", logoText: "TS", color: "#dc2626", region: "Nasional" },
  { id: "spotv", name: "SPOTV", category: "olahraga", description: "SPOTV - Channel olahraga", streamUrl: "http://primestreams.tv:826/live/mookie22/49aV7nBsK4/119515.m3u8", logoText: "SP", color: "#059669", region: "Nasional" },
  { id: "spotv2", name: "SPOTV 2", category: "olahraga", description: "SPOTV 2 - Channel olahraga", streamUrl: "http://primestreams.tv:826/live/mookie22/49aV7nBsK4/119516.m3u8", logoText: "S2", color: "#0284c7", region: "Nasional" },

  // ===== MUSIK =====
  { id: "izzatv", name: "Izzah TV", category: "musik", description: "Izzah TV - TV musik dan hiburan", streamUrl: "https://streaming.radiosalamjambi.com/izzahtv.m3u8", logoText: "IZ", color: "#d97706", region: "Jambi" },
  { id: "madutv", name: "Madu TV", category: "musik", description: "Madu TV - TV musik dan hiburan", streamUrl: "https://re1.siar.us/madutv/hd720/playlist.m3u8", logoText: "MU", color: "#ea580c", region: "Nasional" },
  { id: "musicinfo", name: "Music Info Channel", category: "musik", description: "Music Info Channel - TV musik 24 jam", streamUrl: "https://mic.siar.us/mic/live/mic.m3u8", logoText: "MI", color: "#7c3aed", region: "Nasional", headers: { "http-referrer": "https://mic-indo.com/live" } },
  { id: "lingkartv", name: "Lingkar TV", category: "musik", description: "Lingkar TV - TV musik, berita & religi", streamUrl: "https://lingkartv.my.id/hls/lingkartv.m3u8", logoText: "LK", color: "#0e7490", region: "Nasional" },

  // ===== RELIGI =====
  { id: "alimantv", name: "Al-Iman TV", category: "religi", description: "Al-Iman TV - TV dakwah Islam", streamUrl: "https://tv.aliman.id/aliman/live.m3u8", logoText: "AI", color: "#15803d", region: "Nasional" },
  { id: "albahjahtv", name: "Al-Bahjah TV", category: "religi", description: "Al-Bahjah TV - TV dakwah Nahdlatul Ulama", streamUrl: "http://202.150.161.117:8000/play/AlBahjahTV", logoText: "AB", color: "#166534", region: "Nasional" },
  { id: "alwafatarim", name: "Alwafa Tarim TV", category: "religi", description: "Alwafa Tarim TV - TV dakwah", streamUrl: "https://ammedia.siar.us/ammedia/live/playlist.m3u8", logoText: "AW", color: "#14532d", region: "Nasional" },
  { id: "madanitv", name: "Madani TV", category: "religi", description: "Madani TV - TV Islam Indonesia", streamUrl: "https://stream.asianastream.com/madani/madanitv.smil/playlist.m3u8", logoText: "MD", color: "#065f46", region: "Nasional" },
  { id: "dhammatv", name: "Dhamma TV", category: "religi", description: "Dhamma TV - TV Buddhis Indonesia", streamUrl: "https://b.webcache.maxindo.net.id/dhamma/dhamma.m3u8", logoText: "DH", color: "#d97706", region: "Nasional" },
  { id: "dmireligi", name: "DMI TV", category: "religi", description: "DMI TV - TV dakwah Islam Indonesia", streamUrl: "https://tvstreamcast.com/tawaftv.m3u8", logoText: "DM", color: "#166534", region: "Nasional" },
  { id: "iamchannel", name: "I Am Channel", category: "religi", description: "I Am Channel - TV Kristiani Indonesia", streamUrl: "https://61146e7ab7a66.streamlock.net:8089/tes/1/chunklist.m3u8", logoText: "IA", color: "#0369a1", region: "Nasional", headers: { "http-referrer": "https://iamchannel.org/" } },
  { id: "angeltv", name: "Angel TV", category: "religi", description: "Angel TV Indonesia - TV Kristiani", streamUrl: "https://janya-digimix.akamaized.net/vglive-sk-234616/indonesia/ngrp:angelindonesia_all/playlist.m3u8", logoText: "AG", color: "#7c3aed", region: "Nasional" },
  { id: "mqtv", name: "MQTV", category: "religi", description: "MQTV - TV dakwah dan pendidikan Islam", streamUrl: "https://5bf7b725107e5.streamlock.net/mqtv/mqtv/playlist.m3u8", logoText: "MQ", color: "#166534", region: "Nasional" },
  { id: "mtatv", name: "MTA TV", category: "religi", description: "MTA TV - TV Islam Ahmadiyya", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/mtatv/manifest.mpd", logoText: "MT", color: "#065f46", region: "Nasional" },
  { id: "nabawitv", name: "Nabawi TV", category: "religi", description: "Nabawi TV - TV dakwah Islam", streamUrl: "http://202.150.161.117:8000/play/NabawiTV", logoText: "NB", color: "#14532d", region: "Nasional" },
  { id: "rodjatv", name: "Rodja TV", category: "religi", description: "Rodja TV - TV dakwah Islam Ahlussunnah", streamUrl: "https://rodjatv.com/rodjatv/live.m3u8", logoText: "RJ", color: "#15803d", region: "Nasional" },
  { id: "salamtv", name: "Salam TV", category: "religi", description: "Salam TV - TV dakwah Islam", streamUrl: "https://salamtv.siar.us/live/salamtv.m3u8", logoText: "SL", color: "#065f46", region: "Nasional" },
  { id: "tvmui", name: "TV MUI", category: "religi", description: "TV MUI - TV Majelis Ulama Indonesia", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/muitv/manifest.mpd", logoText: "VM", color: "#14532d", region: "Nasional" },
  { id: "ashiiltv", name: "Ashiil TV", category: "religi", description: "Ashiil TV - TV dakwah Islam", streamUrl: "https://wahyu1ptv.pages.dev/AshiilTV-HD.m3u8", logoText: "AS", color: "#166534", region: "Nasional" },
  { id: "wesaltv", name: "Wesal TV", category: "religi", description: "Wesal TV - TV dakwah Islam", streamUrl: "https://ams.juraganstreaming.com:5443/LiveApp/streams/wesaltv.m3u8", logoText: "WS", color: "#14532d", region: "Nasional" },
  { id: "surautv", name: "Surau TV", category: "religi", description: "Surau TV - TV dakwah Islam", streamUrl: "https://surautv.siar.us/live/surautv.m3u8", logoText: "SR", color: "#15803d", region: "Nasional" },

  // ===== GAYA HIDUP =====
  { id: "biznetadventure", name: "Biznet Adventure", category: "gaya_hidup", description: "Biznet Adventure - TV petualangan dan hiburan", streamUrl: "http://livestream.biznetvideo.net/biznet_adventure/smil:adventure.smil/playlist.m3u8", logoText: "BA", color: "#ea580c", region: "Nasional" },
  { id: "biznetlifestyle", name: "Biznet Lifestyle", category: "gaya_hidup", description: "Biznet Lifestyle - TV gaya hidup", streamUrl: "http://livestream.biznetvideo.net/biznet_lifestyle/smil:lifestyle.smil/index.m3u8", logoText: "BL", color: "#d97706", region: "Nasional" },
  { id: "saliratv", name: "Salira TV", category: "gaya_hidup", description: "Salira TV - TV budaya dan gaya hidup Sunda", streamUrl: "https://live.salira.tv/p/3870/hybrid/play.m3u8", logoText: "SA", color: "#0e7490", region: "Jawa Barat" },
  { id: "allegro", name: "Allegro", category: "gaya_hidup", description: "Allegro - Channel gaya hidup", streamUrl: "https://vodcdn.bamboo-cloud.com/livehls/68c525e1063044539b09c253/master.m3u8", logoText: "AL", color: "#7c3aed", region: "Nasional", headers: { "http-referrer": "https://allegrotelkomvision.renderforestsites.com/" } },

  // ===== BISNIS =====
  { id: "idxchannel", name: "IDX Channel", category: "bisnis", description: "IDX Channel - TV pasar modal dan investasi", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/idx/manifest.mpd", logoText: "IX", color: "#1d4ed8", region: "Nasional" },
  { id: "mbgtv", name: "MBG TV", category: "bisnis", description: "MBG TV - TV legislatif dan pemerintahan", streamUrl: "https://stream.convergen.co/mbg_stream/smil:mbStream.smil/playlist.m3u8", logoText: "MB", color: "#7c3aed", region: "Nasional" },
  { id: "tvrparlemen", name: "TVR Parlemen", category: "bisnis", description: "TVR Parlemen - TV parlemen Indonesia", streamUrl: "https://ssv1.dpr.go.id/golive/livestream/playlist.m3u8", logoText: "VP", color: "#0e7490", region: "Nasional" },

  // ===== DAERAH - Jawa =====
  { id: "jawapostv_sby", name: "Jawa Pos TV Surabaya", category: "daerah", description: "Jawa Pos TV Surabaya - TV lokal Jawa Timur", streamUrl: "http://122.248.43.242:1935/JAWAPOSTVSBY/_definst_/myStream/playlist.m3u8", logoText: "JP", color: "#1d4ed8", region: "Jawa Timur" },
  { id: "jawapostv_jkt", name: "Jawa Pos TV Jakarta", category: "daerah", description: "Jawa Pos TV Jakarta - TV lokal DKI Jakarta", streamUrl: "http://122.248.43.242:1935/JAWAPOSTVJKT/_definst_/myStream/playlist.m3u8", logoText: "JP", color: "#1d4ed8", region: "DKI Jakarta" },
  { id: "jawapostv_madiun", name: "Jawa Pos TV Madiun", category: "daerah", description: "Jawa Pos TV Madiun - TV lokal Jawa Timur", streamUrl: "http://122.248.43.242:1935/JAWAPOSTVMADIUN/_definst_/myStream/playlist.m3u8", logoText: "JP", color: "#1d4ed8", region: "Jawa Timur" },
  { id: "jawapostv_semarang", name: "Jawa Pos TV Semarang", category: "daerah", description: "Jawa Pos TV Semarang - TV lokal Jawa Tengah", streamUrl: "http://122.248.43.242:1935/JAWAPOSTVSEMARANG/_definst_/myStream/playlist.m3u8", logoText: "JP", color: "#1d4ed8", region: "Jawa Tengah" },
  { id: "jawapostv_bali", name: "Jawa Pos TV Bali", category: "daerah", description: "Jawa Pos TV Bali - TV lokal Bali", streamUrl: "http://122.248.43.242:1935/JAWAPOSTVBALI/_definst_/myStream/playlist.m3u8", logoText: "JP", color: "#1d4ed8", region: "Bali" },
  { id: "jawapostv_magelang", name: "Jawa Pos TV Magelang", category: "daerah", description: "Jawa Pos TV Magelang - TV lokal Jawa Tengah", streamUrl: "http://122.248.43.242:1935/JAWAPOSTVMAGELANG/_definst_/myStream/playlist.m3u8", logoText: "JP", color: "#1d4ed8", region: "Jawa Tengah" },
  { id: "bandungtv", name: "Bandung TV", category: "daerah", description: "Bandung TV - TV lokal Jawa Barat", streamUrl: "http://202.150.153.254:65500/bandungtvWEBSITE.m3u8", logoText: "BD", color: "#2563eb", region: "Jawa Barat" },
  { id: "jogjatv", name: "Jogja TV", category: "daerah", description: "Jogja TV - TV lokal Yogyakarta", streamUrl: "https://stream.jogjatv.co.id/jtvlive/stream/index.m3u8", logoText: "JT", color: "#7c3aed", region: "DI Yogyakarta" },
  { id: "jogjaistimewatv", name: "Jogja Istimewa TV", category: "daerah", description: "JITV - TV lokal Yogyakarta", streamUrl: "http://103.255.15.222:1935/tv/jitv_720p/playlist.m3u8", logoText: "JI", color: "#9333ea", region: "DI Yogyakarta" },
  { id: "dhohotv", name: "Dhoho TV", category: "daerah", description: "Dhoho TV - TV lokal Kediri", streamUrl: "https://dhohotv.siar.us/dhohotv/live/playlist.m3u8", logoText: "DH", color: "#ca8a04", region: "Jawa Timur" },
  { id: "dutatv", name: "Duta TV", category: "daerah", description: "Duta TV - TV lokal Indonesia", streamUrl: "https://dutatv.siar.us/dutatv/live/playlist.m3u8", logoText: "DU", color: "#0284c7", region: "Nasional" },
  { id: "jtv", name: "JTV Surabaya", category: "daerah", description: "JTV - TV lokal Surabaya", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/jtv/manifest.mpd", logoText: "JV", color: "#ea580c", region: "Jawa Timur" },
  { id: "jtvkediri", name: "JTV Kediri", category: "daerah", description: "JTV Kediri - TV lokal Jawa Timur", streamUrl: "http://122.248.43.242:1935/JTVKEDIRI/_definst_/myStream/playlist.m3u8", logoText: "JK", color: "#ea580c", region: "Jawa Timur" },
  { id: "jtvmadiun", name: "JTV Madiun", category: "daerah", description: "JTV Madiun - TV lokal Jawa Timur", streamUrl: "http://122.248.43.242:1935/JTVMADIUN/_definst_/myStream/playlist.m3u8", logoText: "JM", color: "#ea580c", region: "Jawa Timur" },
  { id: "jtvmalang", name: "JTV Malang", category: "daerah", description: "JTV Malang - TV lokal Jawa Timur", streamUrl: "http://122.248.43.242:1935/JTVMALANG/_definst_/myStream/playlist.m3u8", logoText: "JL", color: "#ea580c", region: "Jawa Timur" },
  { id: "dmtvmalang", name: "DM TV Malang", category: "daerah", description: "DM TV Malang - TV lokal Jawa Timur", streamUrl: "https://e.siar.us/live/dmtv.m3u8", logoText: "DM", color: "#16a34a", region: "Jawa Timur" },
  { id: "surabayatv", name: "Surabaya TV", category: "daerah", description: "Surabaya TV - TV lokal Jawa Timur", streamUrl: "https://e.siar.us/live/surabayatv.m3u8", logoText: "SB", color: "#dc2626", region: "Jawa Timur" },
  { id: "matrixtv", name: "Matrix TV", category: "daerah", description: "Matrix TV - TV lokal Yogyakarta", streamUrl: "https://stream.matrixtv.id/hls/0/stream.m3u8", logoText: "MX", color: "#0e7490", region: "DI Yogyakarta", headers: { "http-referrer": "https://stream.matrixtv.id/" } },
  { id: "banyumastv", name: "Banyumas TV", category: "daerah", description: "Banyumas TV - TV lokal Jawa Tengah", streamUrl: "https://5bf7b725107e5.streamlock.net/bmstv/bmstv/playlist.m3u8", logoText: "BM", color: "#059669", region: "Jawa Tengah" },
  { id: "semarangtv", name: "Semarang TV", category: "daerah", description: "Semarang TV - TV lokal Jawa Tengah", streamUrl: "http://116.254.112.74/hls/cakralive.m3u8", logoText: "SM", color: "#1d4ed8", region: "Jawa Tengah" },
  { id: "carubantv", name: "Caruban TV", category: "daerah", description: "Caruban TV - TV lokal Jawa Tengah", streamUrl: "https://stream.carubantv.id/hls/0/stream.m3u8", logoText: "CR", color: "#7c3aed", region: "Jawa Tengah", headers: { "http-referrer": "https://stream.carubantv.id" } },
  { id: "kilisucitv", name: "Kilisuci TV", category: "daerah", description: "Kilisuci TV - TV lokal Jawa Timur", streamUrl: "https://5bf7b725107e5.streamlock.net/kstv/kstv/playlist.m3u8", logoText: "KS", color: "#ca8a04", region: "Jawa Timur" },
  { id: "astrobotv", name: "Astro Blitar TV", category: "daerah", description: "Astro Blitar TV - TV lokal Jawa Timur", streamUrl: "https://5bf7b725107e5.streamlock.net/abtv/abtv/playlist.m3u8", logoText: "AB", color: "#0891b2", region: "Jawa Timur", headers: { "http-referrer": "https://abtelevisi.com/" } },
  { id: "jektv", name: "Jek TV", category: "daerah", description: "Jek TV - TV lokal Surabaya", streamUrl: "http://27.124.81.245:1935/jektv/myStream/playlist.m3u8", logoText: "JE", color: "#ea580c", region: "Jawa Timur", headers: { "http-referrer": "http://jektv.co.id/livestreaming/" } },
  { id: "tvku", name: "TVKU", category: "daerah", description: "TVKU - TV lokal Semarang", streamUrl: "https://tvku.tv/hlsstream/hls/live.m3u8", logoText: "TK", color: "#0284c7", region: "Jawa Tengah" },
  { id: "ugtv", name: "UGTV", category: "daerah", description: "UGTV - TV kampus Gunadarma", streamUrl: "https://cdn.gunadarma.ac.id/streams/ugtv/ingestugtv.m3u8", logoText: "UG", color: "#1d4ed8", region: "DKI Jakarta" },
  { id: "jaktv", name: "Jak TV", category: "daerah", description: "Jak TV - TV lokal Jakarta", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/JAK_TV/manifest.mpd", logoText: "JK", color: "#0284c7", region: "DKI Jakarta" },
  { id: "bantentv", name: "Banten TV", category: "daerah", description: "Banten TV - TV lokal Banten", streamUrl: "https://5bf7b725107e5.streamlock.net/bantentv/bantentv/playlist.m3u8", logoText: "BN", color: "#16a34a", region: "Banten" },
  { id: "efarinatv", name: "Efarina TV", category: "daerah", description: "Efarina TV - TV lokal Banten", streamUrl: "https://live.efarinatv.com/hls/bgtaufikganteng.m3u8", logoText: "EF", color: "#ea580c", region: "Banten", headers: { "http-referrer": "https://live.efarinatv.net/" } },
  { id: "brtv", name: "BRTV", category: "daerah", description: "BRTV - TV lokal Jawa Barat", streamUrl: "https://5bf7b725107e5.streamlock.net/brtv/brtv/playlist.m3u8", logoText: "BR", color: "#7c3aed", region: "Jawa Barat" },

  // ===== DAERAH - Stara TV network =====
  { id: "staratv", name: "Stara TV", category: "daerah", description: "Stara TV - TV lokal nasional", streamUrl: "https://stream.staratv.id/hls/0/stream.m3u8", logoText: "ST", color: "#e11d48", region: "Nasional", headers: { "http-referrer": "https://stream.staratv.id/" } },
  { id: "staratvbdg", name: "Stara TV Bandung", category: "daerah", description: "Stara TV Bandung - TV lokal Jawa Barat", streamUrl: "https://bandung.staratv.id/hls/0/stream.m3u8", logoText: "SB", color: "#e11d48", region: "Jawa Barat", headers: { "http-referrer": "https://bandung.staratv.id/" } },
  { id: "staratvjkt", name: "Stara TV Jakarta", category: "daerah", description: "Stara TV Jakarta - TV lokal DKI Jakarta", streamUrl: "https://jakarta.staratv.id/hls/0/stream.m3u8", logoText: "SJ", color: "#e11d48", region: "DKI Jakarta", headers: { "http-referrer": "https://jakarta.staratv.id/" } },
  { id: "staratvmalang", name: "Stara TV Malang", category: "daerah", description: "Stara TV Malang - TV lokal Jawa Timur", streamUrl: "https://malang.staratv.id/hls/0/stream.m3u8", logoText: "SM", color: "#e11d48", region: "Jawa Timur", headers: { "http-referrer": "https://malang.staratv.id/" } },
  { id: "staratvbojonegoro", name: "Stara TV Bojonegoro", category: "daerah", description: "Stara TV Bojonegoro - TV lokal Jawa Timur", streamUrl: "https://bojonegoro.staratv.id/hls/stream.m3u8", logoText: "SB", color: "#e11d48", region: "Jawa Timur", headers: { "http-referrer": "https://bojonegoro.staratv.id/" } },
  { id: "staratvcianjur", name: "Stara TV Cianjur", category: "daerah", description: "Stara TV Cianjur - TV lokal Jawa Barat", streamUrl: "https://cianjur.staratv.id/hls/0/stream.m3u8", logoText: "SC", color: "#e11d48", region: "Jawa Barat", headers: { "http-referrer": "https://cianjur.staratv.id/" } },
  { id: "staratvparahyangan", name: "Stara TV Parahyangan", category: "daerah", description: "Stara TV Parahyangan - TV lokal Jawa Barat", streamUrl: "https://parahyangan.staratv.id/hls/0/stream.m3u8", logoText: "SP", color: "#e11d48", region: "Jawa Barat", headers: { "http-referrer": "https://parahyangan.staratv.id/" } },

  // ===== DAERAH - Sumatera =====
  { id: "padangtv", name: "Padang TV", category: "daerah", description: "Padang TV - TV lokal Sumatera Barat", streamUrl: "http://122.248.43.242:1935/PADANGTV/_definst_/myStream/playlist.m3u8", logoText: "PD", color: "#0e7490", region: "Sumatera Barat" },
  { id: "riautv", name: "Riau TV", category: "daerah", description: "Riau TV - TV lokal Riau", streamUrl: "http://122.248.43.242:1935/RIAUTV/_definst_/myStream/playlist.m3u8", logoText: "RI", color: "#16a34a", region: "Riau" },
  { id: "batamtv", name: "Batam TV", category: "daerah", description: "Batam TV - TV lokal Kepulauan Riau", streamUrl: "http://122.248.43.242:1935/BATAMTV/_definst_/myStream/playlist.m3u8", logoText: "BT", color: "#0284c7", region: "Riau" },
  { id: "sriwijayatv", name: "Sriwijaya TV", category: "daerah", description: "Sriwijaya TV - TV lokal Sumatera Selatan", streamUrl: "https://sriwijayatv.siar.us/live/sriwijayatv.m3u8", logoText: "SW", color: "#dc2626", region: "Sumatera Selatan" },
  { id: "radartv_tasik", name: "Radar Tasikmalaya TV", category: "daerah", description: "Radar Tasikmalaya TV - TV lokal Jawa Barat", streamUrl: "https://v2.siar.us/radartasikmalaya/live/playlist.m3u8", logoText: "RT", color: "#0e7490", region: "Jawa Barat" },
  { id: "jambitv", name: "Jambi TV", category: "daerah", description: "Jambi TV - TV lokal Jambi", streamUrl: "https://ams.juraganstreaming.com:5443/JambiTV/streams/livestream.m3u8", logoText: "JB", color: "#16a34a", region: "Jambi", headers: { "http-referrer": "https://jambitv.co.id/live-tv/" } },
  { id: "pujatv", name: "Puja TV Aceh", category: "daerah", description: "Puja TV Aceh - TV lokal Aceh", streamUrl: "https://v6.siar.us/pujatv/live/chunks.m3u8", logoText: "PJ", color: "#059669", region: "Aceh" },
  { id: "rakyatbengkulu", name: "Rakyat Bengkulu TV", category: "daerah", description: "Rakyat Bengkulu TV - TV lokal Bengkulu", streamUrl: "https://flv.intechmedia.net/live/ch59.m3u8", logoText: "RB", color: "#0e7490", region: "Bengkulu", headers: { "http-referrer": "https://youtv.live/" } },
  { id: "tegartvlampung", name: "Tegar TV Lampung", category: "daerah", description: "Tegar TV Lampung - TV lokal Lampung", streamUrl: "https://5bf7b725107e5.streamlock.net/tegartv/tegartv/playlist.m3u8", logoText: "TG", color: "#16a34a", region: "Lampung" },
  { id: "pjtv", name: "PJTV", category: "daerah", description: "PJTV - TV lokal Jawa Barat", streamUrl: "https://pjtv28uhf.siar.us/live/pjtv28uhf.m3u8", logoText: "PJ", color: "#7c3aed", region: "Jawa Barat", headers: { "http-referrer": "https://pjtv.media/streaming/" } },

  // ===== DAERAH - Kalimantan =====
  { id: "banjartv", name: "Banjar TV", category: "daerah", description: "Banjar TV - TV lokal Kalimantan Selatan", streamUrl: "https://banjartv.siar.us/banjartv/live/playlist.m3u8", logoText: "BJ", color: "#059669", region: "Kalimantan Selatan" },
  { id: "humabetangtv", name: "Huma Betang TV", category: "daerah", description: "Huma Betang TV - TV lokal Kalimantan Tengah", streamUrl: "https://v3.siar.us/humabetangtv/live/playlist.m3u8", logoText: "HB", color: "#b91c1c", region: "Kalimantan Tengah" },
  { id: "pontv", name: "PONTV", category: "daerah", description: "PONTV - TV lokal Kalimantan Barat", streamUrl: "http://122.248.43.242:1935/PONTV/_definst_/myStream/playlist.m3u8", logoText: "PN", color: "#0284c7", region: "Kalimantan Barat" },
  { id: "stv_samarinda", name: "STV Samarinda", category: "daerah", description: "STV - TV lokal Kalimantan Timur", streamUrl: "http://122.248.43.242:1935/SAMARINDATV/_definst_/myStream/playlist.m3u8", logoText: "SV", color: "#7c3aed", region: "Kalimantan Timur" },
  { id: "tvtabalong", name: "TV Tabalong", category: "daerah", description: "TV Tabalong - TV lokal Kalimantan Selatan", streamUrl: "https://5bf7b725107e5.streamlock.net/tvtabalong/tvtabalong/playlist.m3u8", logoText: "TB", color: "#059669", region: "Kalimantan Selatan" },
  { id: "bungotv", name: "Bungo TV", category: "daerah", description: "Bungo TV - TV lokal Jambi", streamUrl: "https://5bf7b725107e5.streamlock.net/bungotv/bungotv/playlist.m3u8", logoText: "BG", color: "#16a34a", region: "Jambi" },
  { id: "balikpappantv", name: "Balikpapan TV", category: "daerah", description: "Balikpapan TV - TV lokal Kalimantan Timur", streamUrl: "https://5bf7b725107e5.streamlock.net/btv/btv/playlist.m3u8", logoText: "BP", color: "#ea580c", region: "Kalimantan Timur" },
  { id: "sampittv", name: "Sampit TV", category: "daerah", description: "Sampit TV - TV lokal Kalimantan Tengah", streamUrl: "https://sampit-tv.siar.us/live/sampit-tv.m3u8", logoText: "SM", color: "#1d4ed8", region: "Kalimantan Tengah" },
  { id: "rrinet", name: "RRI Net", category: "daerah", description: "RRI Net - Radio Republik Indonesia Visual", streamUrl: "https://private-streaming.rri.go.id/memfs/6f77c7b5-feb2-4935-9f89-e7e9fca0a54a_output_0.m3u8", logoText: "RR", color: "#dc2626", region: "Nasional" },

  // ===== DAERAH - Sulawesi =====
  { id: "kawanuatv", name: "Kawanua TV", category: "daerah", description: "Kawanua TV - TV lokal Sulawesi Utara", streamUrl: "http://122.248.43.242:1935/KAWANUATV/_definst_/myStream/playlist.m3u8", logoText: "KW", color: "#16a34a", region: "Sulawesi Utara" },
  { id: "tatv", name: "TATV", category: "daerah", description: "TATV - TV lokal Jawa Tengah", streamUrl: "https://v2.siar.us/tatv/live.sdp/playlist.m3u8", logoText: "TA", color: "#1d4ed8", region: "Jawa Tengah" },
  { id: "fajartv", name: "Fajar TV", category: "daerah", description: "Fajar TV - TV lokal Sulawesi Selatan", streamUrl: "http://122.248.43.242:1935/FAJARTV/_definst_/myStream/playlist.m3u8", logoText: "FJ", color: "#dc2626", region: "Sulawesi Selatan" },
  { id: "celebestv", name: "Celebes TV", category: "daerah", description: "Celebes TV - TV lokal Sulawesi Selatan", streamUrl: "https://ams.juraganstreaming.com:5443/LiveApp/streams/celebesmedia.m3u8", logoText: "CL", color: "#0e7490", region: "Sulawesi Selatan" },
  { id: "sultratv", name: "Sultra TV", category: "daerah", description: "Sultra TV - TV lokal Sulawesi Tenggara", streamUrl: "http://122.248.43.242:1935/SULTRATV/_definst_/myStream/playlist.m3u8", logoText: "ST", color: "#059669", region: "Sulawesi Tenggara" },
  { id: "simpang5tv", name: "Simpang5 TV", category: "daerah", description: "Simpang5 TV - TV lokal", streamUrl: "http://122.248.43.242:1935/SIMPANG5TV/_definst_/myStream/playlist.m3u8", logoText: "S5", color: "#7c3aed", region: "Nasional" },

  // ===== DAERAH - NTT/NTB/Bali/Maluku/Papua =====
  { id: "timortv", name: "Timor TV", category: "daerah", description: "Timor TV - TV lokal NTT", streamUrl: "http://122.248.43.242:1935/TIMORTV/_definst_/myStream/playlist.m3u8", logoText: "TM", color: "#b91c1c", region: "Nusa Tenggara Timur" },
  { id: "balitv", name: "Bali TV", category: "daerah", description: "Bali TV - TV lokal Bali", streamUrl: "https://cdn10jtedge.indihometv.com/atm/DASH/balitv/manifest.mpd", logoText: "BL", color: "#f59e0b", region: "Bali" },
  { id: "atambuatv", name: "Atambua TV", category: "daerah", description: "Atambua TV - TV lokal NTT", streamUrl: "http://122.248.43.242:1935/ATAMBUATV/_definst_/myStream/playlist.m3u8", logoText: "AT", color: "#dc2626", region: "Nusa Tenggara Timur" },
  { id: "davikatv", name: "Davika TV", category: "daerah", description: "Davika TV - TV lokal Jawa Barat", streamUrl: "https://5bf7b725107e5.streamlock.net/davika/davika/playlist.m3u8", logoText: "DV", color: "#7c3aed", region: "Jawa Barat", headers: { "http-referrer": "https://davikatv.co/livestreaming/" } },
  { id: "asthatv", name: "Astha TV", category: "daerah", description: "Astha TV - TV lokal Jawa Timur", streamUrl: "https://hgmtv.com:19360/asthatv/asthatv.m3u8", logoText: "AH", color: "#0e7490", region: "Jawa Timur" },
  { id: "tv9nusantara", name: "TV9 Nusantara", category: "daerah", description: "TV9 Nusantara - TV lokal Jawa Timur", streamUrl: "https://5bf7b725107e5.streamlock.net/tv9/tv9/playlist.m3u8", logoText: "T9", color: "#dc2626", region: "Jawa Timur" },
  { id: "saktitv", name: "Sakti TV", category: "daerah", description: "Sakti TV - TV lokal Jawa Tengah", streamUrl: "https://saktitv.siar.us/saktitv/live/playlist.m3u8", logoText: "SK", color: "#ea580c", region: "Jawa Tengah" },
  { id: "smtv", name: "SM TV", category: "daerah", description: "SM TV - TV lokal Jawa Timur", streamUrl: "https://e.siar.us/live/smtv.m3u8", logoText: "SM", color: "#059669", region: "Jawa Timur", headers: { "http-referrer": "https://smtv.digital/" } },
  { id: "tvmu", name: "TV Mu", category: "daerah", description: "TV Mu - TV lokal Jawa Timur", streamUrl: "https://e.siar.us/live/tvmu.m3u8", logoText: "VM", color: "#0284c7", region: "Jawa Timur" },
  { id: "ktv", name: "KTV", category: "daerah", description: "KTV - TV lokal", streamUrl: "https://flv.intechmedia.net/live/ch118.m3u8", logoText: "KV", color: "#7c3aed", region: "Nasional", headers: { "http-referrer": "https://youtv.live/" } },
  { id: "rinjanitv", name: "Rinjani TV", category: "daerah", description: "Rinjani TV - TV lokal NTB", streamUrl: "https://rinjanitv.cloud/hls/tvkabel.m3u8", logoText: "RN", color: "#059669", region: "Nusa Tenggara Barat" },
  { id: "selaparangtv", name: "Selaparang TV", category: "daerah", description: "Selaparang TV - TV lokal NTB", streamUrl: "https://selaparangtv.siar.us/live/selaparangtv.m3u8", logoText: "SL", color: "#1d4ed8", region: "Nusa Tenggara Barat", headers: { "http-referrer": "https://selaparangtv.net" } },
  { id: "rctv", name: "RCTV", category: "daerah", description: "RCTV - TV lokal Jawa Timur", streamUrl: "https://v10.siar.us/rctv/live/playlist.m3u8", logoText: "RC", color: "#dc2626", region: "Jawa Timur" },
  { id: "pktv", name: "PKTV", category: "daerah", description: "PKTV - TV lokal Kalimantan Timur", streamUrl: "https://streaming.id18.tunnel.my.id/hls/stream.m3u8", logoText: "PK", color: "#1d4ed8", region: "Kalimantan Timur", headers: { "http-referrer": "https://pktvkaltim.com/acara/live-content/?noamp=mobile" } },
  { id: "vtv", name: "VTV", category: "daerah", description: "VTV - TV lokal", streamUrl: "https://flv.intechmedia.net/live/ch107.m3u8", logoText: "VV", color: "#0284c7", region: "Nasional", headers: { "http-referrer": "https://youtv.live/" } },
  { id: "ubtv", name: "UBTV Brawijaya", category: "daerah", description: "UBTV Brawijaya - TV kampus Malang", streamUrl: "https://ubmedcom.siar.us/live/ubmedcom.m3u8", logoText: "UB", color: "#1d4ed8", region: "Jawa Timur", headers: { "http-referrer": "https://tv.ub.ac.id" } },
  { id: "onlinetvnusantara", name: "Online TV Nusantara", category: "daerah", description: "Online TV Nusantara - TV lokal", streamUrl: "https://5bf7b725107e5.streamlock.net/onlinetvnusantara/onlinetvnusantara/playlist.m3u8", logoText: "ON", color: "#0e7490", region: "Nasional" },
  { id: "mgstv", name: "MGS TV", category: "daerah", description: "MGS TV - TV kampus Gunadarma", streamUrl: "https://cdn.gunadarma.ac.id/streams/mgstv/ingestmgstv.m3u8", logoText: "MG", color: "#7c3aed", region: "DKI Jakarta" },
  { id: "sangajitv", name: "Sangaji TV", category: "daerah", description: "Sangaji TV - TV kampus Gunadarma", streamUrl: "https://cdn.gunadarma.ac.id/streams/sangajitv/ingestsangajitv.m3u8", logoText: "SG", color: "#059669", region: "DKI Jakarta" },

  // ===== TVRI - Semua stasiun daerah =====
  { id: "tvri_aceh", name: "TVRI Aceh", category: "tvri", description: "TVRI Aceh - TV publik Provinsi Aceh", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Aceh/hls/Aceh.m3u8", logoText: "AC", color: "#0d9488", region: "Aceh" },
  { id: "tvri_sumut", name: "TVRI Sumatera Utara", category: "tvri", description: "TVRI Sumatera Utara", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sumut/hls/Sumut.m3u8", logoText: "SU", color: "#0d9488", region: "Sumatera Utara" },
  { id: "tvri_sumbar", name: "TVRI Sumatera Barat", category: "tvri", description: "TVRI Sumatera Barat", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sumbar/hls/Sumbar.m3u8", logoText: "SB", color: "#0d9488", region: "Sumatera Barat" },
  { id: "tvri_riau", name: "TVRI Riau", category: "tvri", description: "TVRI Riau", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Riau/hls/Riau.m3u8", logoText: "RI", color: "#0d9488", region: "Riau" },
  { id: "tvri_jambi", name: "TVRI Jambi", category: "tvri", description: "TVRI Jambi", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Jambi/hls/Jambi.m3u8", logoText: "JB", color: "#0d9488", region: "Jambi" },
  { id: "tvri_sumsel", name: "TVRI Sumatera Selatan", category: "tvri", description: "TVRI Sumatera Selatan", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sumsel/hls/Sumsel.m3u8", logoText: "SS", color: "#0d9488", region: "Sumatera Selatan" },
  { id: "tvri_bengkulu", name: "TVRI Bengkulu", category: "tvri", description: "TVRI Bengkulu", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Bengkulu/hls/Bengkulu.m3u8", logoText: "BK", color: "#0d9488", region: "Bengkulu" },
  { id: "tvri_lampung", name: "TVRI Lampung", category: "tvri", description: "TVRI Lampung", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Lampung/hls/Lampung.m3u8", logoText: "LP", color: "#0d9488", region: "Lampung" },
  { id: "tvri_babel", name: "TVRI Bangka Belitung", category: "tvri", description: "TVRI Bangka Belitung", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Babel/hls/Babel.m3u8", logoText: "BB", color: "#0d9488", region: "Bangka Belitung" },
  { id: "tvri_jabar", name: "TVRI Jawa Barat", category: "tvri", description: "TVRI Jawa Barat", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Jabar/hls/Jabar.m3u8", logoText: "JB", color: "#0d9488", region: "Jawa Barat" },
  { id: "tvri_jateng", name: "TVRI Jawa Tengah", category: "tvri", description: "TVRI Jawa Tengah", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Jateng/hls/Jateng.m3u8", logoText: "JT", color: "#0d9488", region: "Jawa Tengah" },
  { id: "tvri_jatim", name: "TVRI Jawa Timur", category: "tvri", description: "TVRI Jawa Timur", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Jatim/hls/Jatim.m3u8", logoText: "JM", color: "#0d9488", region: "Jawa Timur" },
  { id: "tvri_jogja", name: "TVRI Yogyakarta", category: "tvri", description: "TVRI Yogyakarta", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Jogjakarta/hls/Jogjakarta.m3u8", logoText: "JG", color: "#0d9488", region: "DI Yogyakarta" },
  { id: "tvri_dki", name: "TVRI Jakarta", category: "tvri", description: "TVRI DKI Jakarta", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/DKI/hls/DKI.m3u8", logoText: "DK", color: "#0d9488", region: "DKI Jakarta" },
  { id: "tvri_bali", name: "TVRI Bali", category: "tvri", description: "TVRI Bali", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Bali/hls/Bali.m3u8", logoText: "BL", color: "#0d9488", region: "Bali" },
  { id: "tvri_ntb", name: "TVRI NTB", category: "tvri", description: "TVRI Nusa Tenggara Barat", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/NTB/hls/NTB.m3u8", logoText: "NB", color: "#0d9488", region: "Nusa Tenggara Barat" },
  { id: "tvri_ntt", name: "TVRI NTT", category: "tvri", description: "TVRI Nusa Tenggara Timur", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/NTT/hls/NTT.m3u8", logoText: "NT", color: "#0d9488", region: "Nusa Tenggara Timur" },
  { id: "tvri_kalbar", name: "TVRI Kalimantan Barat", category: "tvri", description: "TVRI Kalimantan Barat", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Kalbar/hls/Kalbar.m3u8", logoText: "KB", color: "#0d9488", region: "Kalimantan Barat" },
  { id: "tvri_kalsel", name: "TVRI Kalimantan Selatan", category: "tvri", description: "TVRI Kalimantan Selatan", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Kalsel/hls/Kalsel.m3u8", logoText: "KS", color: "#0d9488", region: "Kalimantan Selatan" },
  { id: "tvri_kalteng", name: "TVRI Kalimantan Tengah", category: "tvri", description: "TVRI Kalimantan Tengah", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Kalteng/hls/Kalteng.m3u8", logoText: "KT", color: "#0d9488", region: "Kalimantan Tengah" },
  { id: "tvri_kaltim", name: "TVRI Kalimantan Timur", category: "tvri", description: "TVRI Kalimantan Timur", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Kaltim/hls/Kaltim.m3u8", logoText: "KI", color: "#0d9488", region: "Kalimantan Timur" },
  { id: "tvri_sulut", name: "TVRI Sulawesi Utara", category: "tvri", description: "TVRI Sulawesi Utara", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sulut/hls/Sulut.m3u8", logoText: "SN", color: "#0d9488", region: "Sulawesi Utara" },
  { id: "tvri_gorontalo", name: "TVRI Gorontalo", category: "tvri", description: "TVRI Gorontalo", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Gorontalo/hls/Gorontalo.m3u8", logoText: "GO", color: "#0d9488", region: "Gorontalo" },
  { id: "tvri_sulbar", name: "TVRI Sulawesi Barat", category: "tvri", description: "TVRI Sulawesi Barat", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sulbar/hls/Sulbar.m3u8", logoText: "SR", color: "#0d9488", region: "Sulawesi Barat" },
  { id: "tvri_sulteng", name: "TVRI Sulawesi Tengah", category: "tvri", description: "TVRI Sulawesi Tengah", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sulteng/hls/Sulteng.m3u8", logoText: "ST", color: "#0d9488", region: "Sulawesi Tengah" },
  { id: "tvri_sulsel", name: "TVRI Sulawesi Selatan", category: "tvri", description: "TVRI Sulawesi Selatan", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sulsel/hls/Sulsel.m3u8", logoText: "SS", color: "#0d9488", region: "Sulawesi Selatan" },
  { id: "tvri_sultra", name: "TVRI Sulawesi Tenggara", category: "tvri", description: "TVRI Sulawesi Tenggara", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Sultra/hls/Sultra.m3u8", logoText: "SG", color: "#0d9488", region: "Sulawesi Tenggara" },
  { id: "tvri_maluku", name: "TVRI Maluku", category: "tvri", description: "TVRI Maluku", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Ambon/hls/Ambon.m3u8", logoText: "ML", color: "#0d9488", region: "Maluku" },
  { id: "tvri_papua", name: "TVRI Papua", category: "tvri", description: "TVRI Papua", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Papua/hls/Papua.m3u8", logoText: "PP", color: "#0d9488", region: "Papua" },
  { id: "tvri_papuabarat", name: "TVRI Papua Barat", category: "tvri", description: "TVRI Papua Barat", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/Pabar/hls/Pabar.m3u8", logoText: "PB", color: "#0d9488", region: "Papua Barat" },
  { id: "tvri_world", name: "TVRI World", category: "tvri", description: "TVRI World - Siaran internasional", streamUrl: "https://ott-balancer.tvri.go.id/live/eds/TVRIWorld/hls/TVRIWorld.m3u8", logoText: "TW", color: "#0d9488", region: "Nasional" },
];
