export interface TVChannel {
  id: string;
  name: string;
  category: string;
  description: string;
  streamUrl: string;
  logoText: string;
  color: string;
  region: string;
}

export const categories = [
  { id: "semua", name: "Semua", icon: "📺" },
  { id: "nasional", name: "Nasional", icon: "🇮🇩" },
  { id: "berita", name: "Berita", icon: "📰" },
  { id: "hiburan", name: "Hiburan", icon: "🎬" },
  { id: "anak", name: "Anak", icon: "🧸" },
  { id: "olahraga", name: "Olahraga", icon: "⚽" },
  { id: "musik", name: "Musik", icon: "🎵" },
  { id: "religi", name: "Religi", icon: "🕌" },
  { id: "daerah", name: "Daerah", icon: "🏝️" },
];

export const channels: TVChannel[] = [
  // ===== NASIONAL =====
  {
    id: "rcti",
    name: "RCTI",
    category: "nasional",
    description: "Stasiun TV swasta pertama di Indonesia",
    streamUrl: "https://rcti-plus.akamaized.net/playlist/rcti2.m3u8",
    logoText: "RC",
    color: "#1e40af",
    region: "Nasional",
  },
  {
    id: "sctv",
    name: "SCTV",
    category: "nasional",
    description: "Surya Citra Televisi - TV swasta populer",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/sctv.m3u8",
    logoText: "SC",
    color: "#d97706",
    region: "Nasional",
  },
  {
    id: "antv",
    name: "ANTV",
    category: "nasional",
    description: "Andalas Televisi - TV swasta Indonesia",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/antv.m3u8",
    logoText: "AN",
    color: "#16a34a",
    region: "Nasional",
  },
  {
    id: "mnctv",
    name: "MNC TV",
    category: "nasional",
    description: "Media Nusantara Citra TV - MNC Group",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/mnctv.m3u8",
    logoText: "MN",
    color: "#2563eb",
    region: "Nasional",
  },
  {
    id: "tvri",
    name: "TVRI",
    category: "nasional",
    description: "Televisi Republik Indonesia - TV pemerintah",
    streamUrl: "https://wz4hk56gb6vn-hls-live.otorid.com/abr/tegal/otostream/otostream_720p/chunklist.m3u8",
    logoText: "TV",
    color: "#1d4ed8",
    region: "Nasional",
  },
  {
    id: "tvriworld",
    name: "TVRI World",
    category: "nasional",
    description: "Siaran internasional TVRI",
    streamUrl: "https://wz4hk56gb6vn-hls-live.otorid.com/abr/tegal/otostream2/otostream2_720p/chunklist.m3u8",
    logoText: "TW",
    color: "#0f766e",
    region: "Nasional",
  },
  {
    id: "rrinet",
    name: "RRI Net",
    category: "nasional",
    description: "Radio Republik Indonesia Network",
    streamUrl: "https://streaming.rri.co.id/rinet.m3u8",
    logoText: "RR",
    color: "#a16207",
    region: "Nasional",
  },
  // ===== BERITA =====
  {
    id: "metrotv",
    name: "Metro TV",
    category: "berita",
    description: "Stasiun TV berita pertama di Indonesia",
    streamUrl: "https://metro-live.akamaized.net/playlist/metro.m3u8",
    logoText: "MT",
    color: "#0284c7",
    region: "Nasional",
  },
  {
    id: "tvone",
    name: "TV One",
    category: "berita",
    description: "TV berita dan olahraga terkini",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/tvone.m3u8",
    logoText: "01",
    color: "#dc2626",
    region: "Nasional",
  },
  {
    id: "inews",
    name: "iNews",
    category: "berita",
    description: "TV berita dari MNC Group",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/inews.m3u8",
    logoText: "iN",
    color: "#b91c1c",
    region: "Nasional",
  },
  {
    id: "kompastv",
    name: "Kompas TV",
    category: "berita",
    description: "TV berita dari Kompas Gramedia",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/kompastv.m3u8",
    logoText: "KT",
    color: "#1d4ed8",
    region: "Nasional",
  },
  {
    id: "beritasatu",
    name: "BeritaSatu",
    category: "berita",
    description: "TV berita bisnis dan ekonomi",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/beritasatu.m3u8",
    logoText: "B1",
    color: "#c2410c",
    region: "Nasional",
  },
  {
    id: "cnnindonesia",
    name: "CNN Indonesia",
    category: "berita",
    description: "TV berita 24 jam terpercaya",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/cnnindonesia.m3u8",
    logoText: "CN",
    color: "#dc2626",
    region: "Nasional",
  },
  {
    id: "cnbcindonesia",
    name: "CNBC Indonesia",
    category: "berita",
    description: "TV berita bisnis dan pasar modal",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/cnbcindonesia.m3u8",
    logoText: "CB",
    color: "#1e40af",
    region: "Nasional",
  },
  // ===== HIBURAN =====
  {
    id: "indosiar",
    name: "Indosiar",
    category: "hiburan",
    description: "TV hiburan dan musik populer",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/indosiar.m3u8",
    logoText: "IS",
    color: "#7c3aed",
    region: "Nasional",
  },
  {
    id: "trans7",
    name: "Trans7",
    category: "hiburan",
    description: "TV hiburan dan edukasi - Trans Corp",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/trans7.m3u8",
    logoText: "T7",
    color: "#ea580c",
    region: "Nasional",
  },
  {
    id: "transtv",
    name: "Trans TV",
    category: "hiburan",
    description: "TV hiburan keluarga - Trans Corp",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/transtv.m3u8",
    logoText: "TT",
    color: "#ca8a04",
    region: "Nasional",
  },
  {
    id: "gtv",
    name: "GTV",
    category: "hiburan",
    description: "TV hiburan untuk anak muda & keluarga",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/gtv.m3u8",
    logoText: "GT",
    color: "#059669",
    region: "Nasional",
  },
  // ===== ANAK =====
  {
    id: "animax",
    name: "Animax",
    category: "anak",
    description: "TV anime dan kartun terpopuler",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/animax.m3u8",
    logoText: "AX",
    color: "#7c3aed",
    region: "Asia",
  },
  {
    id: "nickelodeon",
    name: "Nickelodeon",
    category: "anak",
    description: "TV anak terpopuler di dunia",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/nickelodeon.m3u8",
    logoText: "NK",
    color: "#ea580c",
    region: "Asia",
  },
  {
    id: "spacetoon",
    name: "Spacetoon",
    category: "anak",
    description: "TV anak dan keluarga islami",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/spacetoon.m3u8",
    logoText: "ST",
    color: "#059669",
    region: "Asia",
  },
  // ===== OLAHRAGA =====
  {
    id: "beinsport1",
    name: "beIN Sports 1",
    category: "olahraga",
    description: "Siaran olahraga internasional",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/beinsport1.m3u8",
    logoText: "B1",
    color: "#6d28d9",
    region: "Asia",
  },
  {
    id: "beinsport2",
    name: "beIN Sports 2",
    category: "olahraga",
    description: "Siaran olahraga tambahan",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/beinsport2.m3u8",
    logoText: "B2",
    color: "#7c3aed",
    region: "Asia",
  },
  // ===== MUSIK =====
  {
    id: "mtv",
    name: "MTV",
    category: "musik",
    description: "TV musik dan hiburan pemuda",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/mtv.m3u8",
    logoText: "MV",
    color: "#2563eb",
    region: "Asia",
  },
  {
    id: "channelv",
    name: "Channel V",
    category: "musik",
    description: "TV musik internasional",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/channelv.m3u8",
    logoText: "CV",
    color: "#16a34a",
    region: "Asia",
  },
  // ===== RELIGI =====
  {
    id: "tvmu",
    name: "TV Mu",
    category: "religi",
    description: "Televisi Muhammadiyah",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/tvmu.m3u8",
    logoText: "MU",
    color: "#15803d",
    region: "Nasional",
  },
  {
    id: "rodjatv",
    name: "Rodja TV",
    category: "religi",
    description: "TV dakwah salafy",
    streamUrl: "https://rodja.tv/live/rodjatv.m3u8",
    logoText: "RJ",
    color: "#166534",
    region: "Nasional",
  },
  // ===== DAERAH =====
  {
    id: "jaktv",
    name: "Jak TV",
    category: "daerah",
    description: "TV lokal Jakarta",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/jaktv.m3u8",
    logoText: "JK",
    color: "#ea580c",
    region: "DKI Jakarta",
  },
  {
    id: "bandungtv",
    name: "Bandung TV",
    category: "daerah",
    description: "TV lokal Jawa Barat",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/bandungtv.m3u8",
    logoText: "BD",
    color: "#1d4ed8",
    region: "Jawa Barat",
  },
  {
    id: "suryatv",
    name: "Surya TV",
    category: "daerah",
    description: "TV lokal Surabaya",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/suryatv.m3u8",
    logoText: "SY",
    color: "#ca8a04",
    region: "Jawa Timur",
  },
  {
    id: "balitv",
    name: "Bali TV",
    category: "daerah",
    description: "TV lokal Pulau Dewata",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/balitv.m3u8",
    logoText: "BL",
    color: "#ea580c",
    region: "Bali",
  },
  {
    id: "makassartv",
    name: "Makassar TV",
    category: "daerah",
    description: "TV lokal Sulawesi Selatan",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/makassartv.m3u8",
    logoText: "MK",
    color: "#dc2626",
    region: "Sulawesi Selatan",
  },
  {
    id: "medantv",
    name: "Medan TV",
    category: "daerah",
    description: "TV lokal Sumatera Utara",
    streamUrl: "https://d2k4snkzuy1c5d.cloudfront.net/medantv.m3u8",
    logoText: "MD",
    color: "#059669",
    region: "Sumatera Utara",
  },
];
